export default [{ key: "9mobile_9payment_service_bank", label: "9mobile 9Payment Service Bank" },
{ key: "abbey_mortgage_bank", label: "Abbey Mortgage Bank" },
{ key: "above_only_mfb", label: "Above Only MFB" },
{ key: "abulesoro_mfb", label: "Abulesoro MFB" },
{ key: "access_bank", label: "Access Bank" },
{ key: "access_bank_(diamond)", label: "Access Bank (Diamond)" },
{ key: "accion_microfinance_bank", label: "Accion Microfinance Bank" },
{ key: "ag_mortgage_bank", label: "AG Mortgage Bank" },
{ key: "ahmadu_bello_university_microfinance_bank", label: "Ahmadu Bello University Microfinance Bank" },
{ key: "airtel_smartcash_psb", label: "Airtel Smartcash PSB" },
{ key: "aku_microfinance_bank", label: "AKU Microfinance Bank" },
{ key: "akuchukwu_microfinance_bank_limited", label: "Akuchukwu Microfinance Bank Limited" },
{ key: "alat_by_wema", label: "ALAT by WEMA" },
{ key: "amegy_microfinance_bank", label: "Amegy Microfinance Bank" },
{ key: "amju_unique_mfb", label: "Amju Unique MFB" },
{ key: "ampersand_microfinance_bank", label: "AMPERSAND MICROFINANCE BANK" },
{ key: "aramoko_mfb", label: "Aramoko MFB" },
{ key: "aso_savings_and_loans", label: "ASO Savings and Loans" },
{ key: "astrapolaris_mfb_ltd", label: "Astrapolaris MFB LTD" },
{ key: "avuenegbe_microfinance_bank", label: "AVUENEGBE MICROFINANCE BANK" },
{ key: "awacash_microfinance_bank", label: "AWACASH MICROFINANCE BANK" },
{ key: "bainescredit_mfb", label: "Bainescredit MFB" },
{ key: "banc_corp_microfinance_bank", label: "Banc Corp Microfinance Bank" },
{ key: "baobab_microfinance_bank", label: "Baobab Microfinance Bank" },
{ key: "bellbank_microfinance_bank", label: "BellBank Microfinance Bank" },
{ key: "benysta_microfinance_bank_limited", label: "Benysta Microfinance Bank Limited" },
{ key: "beststar_microfinance_bank", label: "Beststar Microfinance Bank" },
{ key: "bowen_microfinance_bank", label: "Bowen Microfinance Bank" },
{ key: "branch_international_financial_services_limited", label: "Branch International Financial Services Limited" },
{ key: "carbon", label: "Carbon" },
{ key: "cashbridge_microfinance_bank_limited", label: "Cashbridge Microfinance Bank Limited" },
{ key: "cashconnect_mfb", label: "CASHCONNECT MFB" },
{ key: "cemcs_microfinance_bank", label: "CEMCS Microfinance Bank" },
{ key: "chanelle_microfinance_bank_limited", label: "Chanelle Microfinance Bank Limited" },
{ key: "chikum_microfinance_bank", label: "Chikum Microfinance bank" },
{ key: "citibank_nigeria", label: "Citibank Nigeria" },
{ key: "citycode_mortage_bank", label: "CITYCODE MORTAGE BANK" },
{ key: "consumer_microfinance_bank", label: "Consumer Microfinance Bank" },
{ key: "corestep_mfb", label: "Corestep MFB" },
{ key: "coronation_merchant_bank", label: "Coronation Merchant Bank" },
{ key: "county_finance_limited", label: "County Finance Limited" },
{ key: "crescent_mfb", label: "Crescent MFB" },
{ key: "crust_microfinance_bank", label: "Crust Microfinance Bank" },
{ key: "davenport_microfinance_bank", label: "Davenport MICROFINANCE BANK" },
{ key: "dot_microfinance_bank", label: "Dot Microfinance Bank" },
{ key: "ecobank_nigeria", label: "Ecobank Nigeria" },
{ key: "ekimogun_mfb", label: "Ekimogun MFB" },
{ key: "ekondo_microfinance_bank", label: "Ekondo Microfinance Bank" },
{ key: "excel_finance_bank", label: "EXCEL FINANCE BANK" },
{ key: "eyowo", label: "Eyowo" },
{ key: "fairmoney_microfinance_bank", label: "Fairmoney Microfinance Bank" },
{ key: "fedeth_mfb", label: "Fedeth MFB" },
{ key: "fidelity_bank", label: "Fidelity Bank" },
{ key: "firmus_mfb", label: "Firmus MFB" },
{ key: "first_bank_of_nigeria", label: "First Bank of Nigeria" },
{ key: "first_city_monument_bank", label: "First City Monument Bank" },
{ key: "first_royal_microfinance_bank", label: "FIRST ROYAL MICROFINANCE BANK" },
{ key: "firsttrust_mortgage_bank_nigeria", label: "FirstTrust Mortgage Bank Nigeria" },
{ key: "flourish_mfb", label: "FLOURISH MFB" },
{ key: "fsdh_merchant_bank_limited", label: "FSDH Merchant Bank Limited" },
{ key: "futminna_microfinance_bank", label: "FUTMINNA MICROFINANCE BANK" },
{ key: "gateway_mortgage_bank_ltd", label: "Gateway Mortgage Bank LTD" },
{ key: "globus_bank", label: "Globus Bank" },
{ key: "goldman_mfb", label: "Goldman MFB" },
{ key: "gomoney", label: "GoMoney" },
{ key: "good_shepherd_microfinance_bank", label: "GOOD SHEPHERD MICROFINANCE BANK" },
{ key: "goodnews_microfinance_bank", label: "Goodnews Microfinance Bank" },
{ key: "greenwich_merchant_bank", label: "Greenwich Merchant Bank" },
{ key: "guaranty_trust_bank", label: "Guaranty Trust Bank" },
{ key: "hackman_microfinance_bank", label: "Hackman Microfinance Bank" },
{ key: "hasal_microfinance_bank", label: "Hasal Microfinance Bank" },
{ key: "hopepsb", label: "HopePSB" },
{ key: "ibile_microfinance_bank", label: "Ibile Microfinance Bank" },
{ key: "ikoyi_osun_mfb", label: "Ikoyi Osun MFB" },
{ key: "ilaro_poly_microfinance_bank", label: "Ilaro Poly Microfinance Bank" },
{ key: "imowo_mfb", label: "Imowo MFB" },
{ key: "imperial_homes_mortage_bank", label: "IMPERIAL HOMES MORTAGE BANK" },
{ key: "infinity_mfb", label: "Infinity MFB" },
{ key: "jaiz_bank", label: "Jaiz Bank" },
{ key: "kadpoly_mfb", label: "Kadpoly MFB" },
{ key: "kanopoly_mfb", label: "KANOPOLY MFB" },
{ key: "keystone_bank", label: "Keystone Bank" },
{ key: "kongapay_(kongapay_technologies_limited)(formerly_zinternet)", label: "KONGAPAY (Kongapay Technologies Limited)(formerly Zinternet)" },
{ key: "kredi_money_mfb_ltd", label: "Kredi Money MFB LTD" },
{ key: "kuda_bank", label: "Kuda Bank" },
{ key: "lagos_building_investment_company_plc.", label: "Lagos Building Investment Company Plc." },
{ key: "links_mfb", label: "Links MFB" },
{ key: "living_trust_mortgage_bank", label: "Living Trust Mortgage Bank" },
{ key: "loma_mfb", label: "LOMA MFB" },
{ key: "lotus_bank", label: "Lotus Bank" },
{ key: "mainstreet_microfinance_bank", label: "MAINSTREET MICROFINANCE BANK" },
{ key: "mayfair_mfb", label: "Mayfair MFB" },
{ key: "mint_mfb", label: "Mint MFB" },
{ key: "money_master_psb", label: "Money Master PSB" },
{ key: "moniepoint_mfb", label: "Moniepoint MFB" },
{ key: "mtn_momo_psb", label: "MTN Momo PSB" },
{ key: "mutual_benefits_microfinance_bank", label: "MUTUAL BENEFITS MICROFINANCE BANK" },
{ key: "ndcc_microfinance_bank", label: "NDCC MICROFINANCE BANK" },
{ key: "net_microfinance_bank", label: "NET MICROFINANCE BANK" },
{ key: "nigerian_navy_microfinance_bank_limited", label: "Nigerian Navy Microfinance Bank Limited" },
{ key: "npf_microfinance_bank", label: "NPF MICROFINANCE BANK" },
{ key: "opay_digital_services_limited_(opay)", label: "OPay Digital Services Limited (OPay)" },
{ key: "optimus_bank_limited", label: "Optimus Bank Limited" },
{ key: "paga", label: "Paga" },
{ key: "palmpay", label: "PalmPay" },
{ key: "parallex_bank", label: "Parallex Bank" },
{ key: "parkway_-_readycash", label: "Parkway - ReadyCash" },
{ key: "pathfinder_microfinance_bank_limited", label: "PATHFINDER MICROFINANCE BANK LIMITED" },
{ key: "paystack-titan", label: "Paystack-Titan" },
{ key: "peace_microfinance_bank", label: "Peace Microfinance Bank" },
{ key: "pecantrust_microfinance_bank_limited", label: "PECANTRUST MICROFINANCE BANK LIMITED" },
{ key: "personal_trust_mfb", label: "Personal Trust MFB" },
{ key: "petra_mircofinance_bank_plc", label: "Petra Mircofinance Bank Plc" },
{ key: "pfi_finance_company_limited", label: "PFI FINANCE COMPANY LIMITED" },
{ key: "platinum_mortgage_bank", label: "Platinum Mortgage Bank" },
{ key: "pocket_app", label: "Pocket App" },
{ key: "polaris_bank", label: "Polaris Bank" },
{ key: "polyunwana_mfb", label: "Polyunwana MFB" },
{ key: "premiumtrust_bank", label: "PremiumTrust Bank" },
{ key: "prosperis_finance_limited", label: "PROSPERIS FINANCE LIMITED" },
{ key: "providus_bank", label: "Providus Bank" },
{ key: "quickfund_mfb", label: "QuickFund MFB" },
{ key: "rand_merchant_bank", label: "Rand Merchant Bank" },
{ key: "randalpha_microfinance_bank", label: "RANDALPHA MICROFINANCE BANK" },
{ key: "refuge_mortgage_bank", label: "Refuge Mortgage Bank" },
{ key: "rehoboth_microfinance_bank", label: "REHOBOTH MICROFINANCE BANK" },
{ key: "rephidim_microfinance_bank", label: "Rephidim Microfinance Bank" },
{ key: "rigo_microfinance_bank_limited", label: "Rigo Microfinance Bank Limited" },
{ key: "rockshield_microfinance_bank", label: "ROCKSHIELD MICROFINANCE BANK" },
{ key: "rubies_mfb", label: "Rubies MFB" },
{ key: "safe_haven_mfb", label: "Safe Haven MFB" },
{ key: "safe_haven_microfinance_bank_limited", label: "Safe Haven Microfinance Bank Limited" },
{ key: "sage_grey_finance_limited", label: "SAGE GREY FINANCE LIMITED" },
{ key: "shield_mfb", label: "Shield MFB" },
{ key: "signature_bank_ltd", label: "Signature Bank Ltd" },
{ key: "solid_allianze_mfb", label: "Solid Allianze MFB" },
{ key: "solid_rock_mfb", label: "Solid Rock MFB" },
{ key: "sparkle_microfinance_bank", label: "Sparkle Microfinance Bank" },
{ key: "stanbic_ibtc_bank", label: "Stanbic IBTC Bank" },
{ key: "standard_chartered_bank", label: "Standard Chartered Bank" },
{ key: "stanford_microfinance_bank", label: "STANFORD MICROFINANCE BANK" },
{ key: "stateside_microfinance_bank", label: "STATESIDE MICROFINANCE BANK" },
{ key: "stellas_mfb", label: "Stellas MFB" },
{ key: "sterling_bank", label: "Sterling Bank" },
{ key: "suntrust_bank", label: "Suntrust Bank" },
{ key: "supreme_mfb", label: "Supreme MFB" },
{ key: "taj_bank", label: "TAJ Bank" },
{ key: "tangerine_money", label: "Tangerine Money" },
{ key: "tcf_mfb", label: "TCF MFB" },
{ key: "titan_bank", label: "Titan Bank" },
{ key: "u&c_microfinance_bank_ltd_(u_and_c_mfb)", label: "U&C Microfinance Bank Ltd (U AND C MFB)" },
{ key: "uhuru_mfb", label: "Uhuru MFB" },
{ key: "unaab_microfinance_bank_limited", label: "Unaab Microfinance Bank Limited" },
{ key: "unical_mfb", label: "Unical MFB" },
{ key: "unilag_microfinance_bank", label: "Unilag Microfinance Bank" },
{ key: "union_bank_of_nigeria", label: "Union Bank of Nigeria" },
{ key: "united_bank_for_africa", label: "United Bank For Africa" },
{ key: "unity_bank", label: "Unity Bank" },
{ key: "uzondu_microfinance_bank_awka_anambra_state", label: "Uzondu Microfinance Bank Awka Anambra State" },
{ key: "vale_finance_limited", label: "Vale Finance Limited" },
{ key: "vfd_microfinance_bank_limited", label: "VFD Microfinance Bank Limited" },
{ key: "waya_microfinance_bank", label: "Waya Microfinance Bank" },
{ key: "wema_bank", label: "Wema Bank" },
{ key: "zenith_bank", label: "Zenith Bank" }]