export default [{
  "state": "adamawa",
  "cities": [
    { "key": "Demsa", "label": "Demsa" },
    { "key": "Fufure", "label": "Fufure" },
    { "key": "Ganye", "label": "Ganye" },
    { "key": "Gayuk", "label": "Gayuk" },
    { "key": "Gombi", "label": "Gombi" },
    { "key": "Grie", "label": "Grie" },
    { "key": "Hong", "label": "Hong" },
    { "key": "Jada", "label": "Jada" },
    { "key": "Larmurde", "label": "Larmurde" },
    { "key": "Madagali", "label": "Madagali" },
    { "key": "Maiha", "label": "Maiha" },
    { "key": "Mayo Belwa", "label": "Mayo Belwa" },
    { "key": "Michika", "label": "Michika" },
    { "key": "Mubi North", "label": "Mubi North" },
    { "key": "Mubi South", "label": "Mubi South" },
    { "key": "Numan", "label": "Numan" },
    { "key": "Shelleng", "label": "Shelleng" },
    { "key": "Song", "label": "Song" },
    { "key": "Toungo", "label": "Toungo" },
    { "key": "Yola North", "label": "Yola North" },
    { "key": "Yola South", "label": "Yola South" }]
},
{
  "state": "akwa_ibom",
  "cities": [
    { "key": "Abak", "label": "Abak" },
    { "key": "Eastern Obolo", "label": "Eastern Obolo" },
    { "key": "Eket", "label": "Eket" },
    { "key": "Esit Eket", "label": "Esit Eket" },
    { "key": "Essien Udim", "label": "Essien Udim" },
    { "key": "Etim Ekpo", "label": "Etim Ekpo" },
    { "key": "Etinan", "label": "Etinan" },
    { "key": "Ibeno", "label": "Ibeno" },
    { "key": "Ibesikpo Asutan", "label": "Ibesikpo Asutan" },
    { "key": "Ibiono-Ibom", "label": "Ibiono-Ibom" },
    { "key": "Ikot Abasi", "label": "Ikot Abasi" },
    { "key": "Ika", "label": "Ika" },
    { "key": "Ikono", "label": "Ikono" },
    { "key": "Ikot Ekpene", "label": "Ikot Ekpene" },
    { "key": "Ini", "label": "Ini" },
    { "key": "Mkpat-Enin", "label": "Mkpat-Enin" },
    { "key": "Itu", "label": "Itu" },
    { "key": "Mbo", "label": "Mbo" },
    { "key": "Nsit-Atai", "label": "Nsit-Atai" },
    { "key": "Nsit-Ibom", "label": "Nsit-Ibom" },
    { "key": "Nsit-Ubium", "label": "Nsit-Ubium" },
    { "key": "Obot Akara", "label": "Obot Akara" },
    { "key": "Okobo", "label": "Okobo" },
    { "key": "Onna", "label": "Onna" },
    { "key": "Oron", "label": "Oron" },
    { "key": "Udung-Uko", "label": "Udung-Uko" },
    { "key": "Ukanafun", "label": "Ukanafun" },
    { "key": "Oruk Anam", "label": "Oruk Anam" },
    { "key": "Uruan", "label": "Uruan" },
    { "key": "Urue-Offong/Oruko", "label": "Urue-Offong/Oruko" },
    { "key": "Uyo", "label": "Uyo" }]
},
{
  "state": "anambra",
  "cities": [
    { "key": "Aguata", "label": "Aguata" },
    { "key": "Anambra East", "label": "Anambra East" },
    { "key": "Anaocha", "label": "Anaocha" },
    { "key": "Awka North", "label": "Awka North" },
    { "key": "Anambra West", "label": "Anambra West" },
    { "key": "Awka South", "label": "Awka South" },
    { "key": "Ayamelum", "label": "Ayamelum" },
    { "key": "Dunukofia", "label": "Dunukofia" },
    { "key": "Ekwusigo", "label": "Ekwusigo" },
    { "key": "Idemili North", "label": "Idemili North" },
    { "key": "Idemili South", "label": "Idemili South" },
    { "key": "Ihiala", "label": "Ihiala" },
    { "key": "Njikoka", "label": "Njikoka" },
    { "key": "Nnewi North", "label": "Nnewi North" },
    { "key": "Nnewi South", "label": "Nnewi South" },
    { "key": "Ogbaru", "label": "Ogbaru" },
    { "key": "Onitsha North", "label": "Onitsha North" },
    { "key": "Onitsha South", "label": "Onitsha South" },
    { "key": "Orumba North", "label": "Orumba North" },
    { "key": "Orumba South", "label": "Orumba South" },
    { "key": "Oyi", "label": "Oyi" }]
},
{
  "state": "ogun",
  "cities": [
    { "key": "Abeokuta North", "label": "Abeokuta North" },
    { "key": "Abeokuta South", "label": "Abeokuta South" },
    { "key": "Ado-Odo/Ota", "label": "Ado-Odo/Ota" },
    { "key": "Egbado North", "label": "Egbado North" },
    { "key": "Ewekoro", "label": "Ewekoro" },
    { "key": "Egbado South", "label": "Egbado South" },
    { "key": "Ijebu North", "label": "Ijebu North" },
    { "key": "Ijebu East", "label": "Ijebu East" },
    { "key": "Ifo", "label": "Ifo" },
    { "key": "Ijebu Ode", "label": "Ijebu Ode" },
    { "key": "Ijebu North East", "label": "Ijebu North East" },
    { "key": "Imeko Afon", "label": "Imeko Afon" },
    { "key": "Ikenne", "label": "Ikenne" },
    { "key": "Ipokia", "label": "Ipokia" },
    { "key": "Odeda", "label": "Odeda" },
    { "key": "Obafemi Owode", "label": "Obafemi Owode" },
    { "key": "Odogbolu", "label": "Odogbolu" },
    { "key": "Remo North", "label": "Remo North" },
    { "key": "Ogun Waterside", "label": "Ogun Waterside" },
    { "key": "Shagamu", "label": "Shagamu" }]
},
{
  "state": "ondo",
  "cities": [
    { "key": "Akoko North-East", "label": "Akoko North-East" },
    { "key": "Akoko North-West", "label": "Akoko North-West" },
    { "key": "Akoko South-West", "label": "Akoko South-West" },
    { "key": "Akoko South-East", "label": "Akoko South-East" },
    { "key": "Akure North", "label": "Akure North" },
    { "key": "Akure South", "label": "Akure South" },
    { "key": "Ese Odo", "label": "Ese Odo" },
    { "key": "Idanre", "label": "Idanre" },
    { "key": "Ifedore", "label": "Ifedore" },
    { "key": "Ilaje", "label": "Ilaje" },
    { "key": "Irele", "label": "Irele" },
    { "key": "Ile Oluji/Okeigbo", "label": "Ile Oluji/Okeigbo" },
    { "key": "Odigbo", "label": "Odigbo" },
    { "key": "Okitipupa", "label": "Okitipupa" },
    { "key": "Ondo West", "label": "Ondo West" },
    { "key": "Ose", "label": "Ose" },
    { "key": "Ondo East", "label": "Ondo East" },
    { "key": "Owo", "label": "Owo" }]
},
{
  "state": "rivers",
  "cities": [
    { "key": "Abua/Odual", "label": "Abua/Odual" },
    { "key": "Ahoada East", "label": "Ahoada East" },
    { "key": "Ahoada West", "label": "Ahoada West" },
    { "key": "Andoni", "label": "Andoni" },
    { "key": "Akuku-Toru", "label": "Akuku-Toru" },
    { "key": "Asari-Toru", "label": "Asari-Toru" },
    { "key": "Bonny", "label": "Bonny" },
    { "key": "Degema", "label": "Degema" },
    { "key": "Emuoha", "label": "Emuoha" },
    { "key": "Eleme", "label": "Eleme" },
    { "key": "Ikwerre", "label": "Ikwerre" },
    { "key": "Etche", "label": "Etche" },
    { "key": "Gokana", "label": "Gokana" },
    { "key": "Khana", "label": "Khana" },
    { "key": "Obio/Akpor", "label": "Obio/Akpor" },
    { "key": "Ogba/Egbema/Ndoni", "label": "Ogba/Egbema/Ndoni" },
    { "key": "Ogu/Bolo", "label": "Ogu/Bolo" },
    { "key": "Okrika", "label": "Okrika" },
    { "key": "Omuma", "label": "Omuma" },
    { "key": "Opobo/Nkoro", "label": "Opobo/Nkoro" },
    { "key": "Oyigbo", "label": "Oyigbo" },
    { "key": "Port Harcourt", "label": "Port Harcourt" },
    { "key": "Tai", "label": "Tai" }]
},
{
  "state": "bauchi",
  "cities": [
    { "key": "Alkaleri", "label": "Alkaleri" },
    { "key": "Bauchi", "label": "Bauchi" },
    { "key": "Bogoro", "label": "Bogoro" },
    { "key": "Damban", "label": "Damban" },
    { "key": "Darazo", "label": "Darazo" },
    { "key": "Dass", "label": "Dass" },
    { "key": "Gamawa", "label": "Gamawa" },
    { "key": "Ganjuwa", "label": "Ganjuwa" },
    { "key": "Giade", "label": "Giade" },
    { "key": "Itas/Gadau", "label": "Itas/Gadau" },
    { "key": "Jama'are", "label": "Jama'are" },
    { "key": "Katagum", "label": "Katagum" },
    { "key": "Kirfi", "label": "Kirfi" },
    { "key": "Misau", "label": "Misau" },
    { "key": "Ningi", "label": "Ningi" },
    { "key": "Shira", "label": "Shira" },
    { "key": "Tafawa Balewa", "label": "Tafawa Balewa" },
    { "key": "Toro", "label": "Toro" },
    { "key": "Warji", "label": "Warji" },
    { "key": "Zaki", "label": "Zaki" }]
},
{
  "state": "benue",
  "cities": [
    { "key": "Agatu", "label": "Agatu" },
    { "key": "Apa", "label": "Apa" },
    { "key": "Ado", "label": "Ado" },
    { "key": "Buruku", "label": "Buruku" },
    { "key": "Gboko", "label": "Gboko" },
    { "key": "Guma", "label": "Guma" },
    { "key": "Gwer East", "label": "Gwer East" },
    { "key": "Gwer West", "label": "Gwer West" },
    { "key": "Katsina-Ala", "label": "Katsina-Ala" },
    { "key": "Konshisha", "label": "Konshisha" },
    { "key": "Kwande", "label": "Kwande" },
    { "key": "Logo", "label": "Logo" },
    { "key": "Makurdi", "label": "Makurdi" },
    { "key": "Obi", "label": "Obi" },
    { "key": "Ogbadibo", "label": "Ogbadibo" },
    { "key": "Ohimini", "label": "Ohimini" },
    { "key": "Oju", "label": "Oju" },
    { "key": "Okpokwu", "label": "Okpokwu" },
    { "key": "Oturkpo", "label": "Oturkpo" },
    { "key": "Tarka", "label": "Tarka" },
    { "key": "Ukum", "label": "Ukum" },
    { "key": "Ushongo", "label": "Ushongo" },
    { "key": "Vandeikya", "label": "Vandeikya" }]
},
{
  "state": "borno",
  "cities": [
    { "key": "Abadam", "label": "Abadam" },
    { "key": "Askira/Uba", "label": "Askira/Uba" },
    { "key": "Bama", "label": "Bama" },
    { "key": "Bayo", "label": "Bayo" },
    { "key": "Biu", "label": "Biu" },
    { "key": "Chibok", "label": "Chibok" },
    { "key": "Damboa", "label": "Damboa" },
    { "key": "Dikwa", "label": "Dikwa" },
    { "key": "Guzamala", "label": "Guzamala" },
    { "key": "Gubio", "label": "Gubio" },
    { "key": "Hawul", "label": "Hawul" },
    { "key": "Gwoza", "label": "Gwoza" },
    { "key": "Jere", "label": "Jere" },
    { "key": "Kaga", "label": "Kaga" },
    { "key": "Kala/Balge", "label": "Kala/Balge" },
    { "key": "Konduga", "label": "Konduga" },
    { "key": "Kukawa", "label": "Kukawa" },
    { "key": "Kwaya Kusar", "label": "Kwaya Kusar" },
    { "key": "Mafa", "label": "Mafa" },
    { "key": "Magumeri", "label": "Magumeri" },
    { "key": "Maiduguri", "label": "Maiduguri" },
    { "key": "Mobbar", "label": "Mobbar" },
    { "key": "Marte", "label": "Marte" },
    { "key": "Monguno", "label": "Monguno" },
    { "key": "Ngala", "label": "Ngala" },
    { "key": "Nganzai", "label": "Nganzai" },
    { "key": "Shani", "label": "Shani" }]
},
{
  "state": "bayelsa",
  "cities": [
    { "key": "Brass", "label": "Brass" },
    { "key": "Ekeremor", "label": "Ekeremor" },
    { "key": "Kolokuma/Opokuma", "label": "Kolokuma/Opokuma" },
    { "key": "Nembe", "label": "Nembe" },
    { "key": "Ogbia", "label": "Ogbia" },
    { "key": "Sagbama", "label": "Sagbama" },
    { "key": "Southern Ijaw", "label": "Southern Ijaw" },
    { "key": "Yenagoa", "label": "Yenagoa" }]
},
{
  "state": "cross_river",
  "cities": [
    { "key": "Abi", "label": "Abi" },
    { "key": "Akamkpa", "label": "Akamkpa" },
    { "key": "Akpabuyo", "label": "Akpabuyo" },
    { "key": "Bakassi", "label": "Bakassi" },
    { "key": "Bekwarra", "label": "Bekwarra" },
    { "key": "Biase", "label": "Biase" },
    { "key": "Boki", "label": "Boki" },
    { "key": "Calabar Municipal", "label": "Calabar Municipal" },
    { "key": "Calabar South", "label": "Calabar South" },
    { "key": "Etung", "label": "Etung" },
    { "key": "Ikom", "label": "Ikom" },
    { "key": "Obanliku", "label": "Obanliku" },
    { "key": "Obubra", "label": "Obubra" },
    { "key": "Obudu", "label": "Obudu" },
    { "key": "Odukpani", "label": "Odukpani" },
    { "key": "Ogoja", "label": "Ogoja" },
    { "key": "Yakuur", "label": "Yakuur" },
    { "key": "Yala", "label": "Yala" }]
},
{
  "state": "delta",
  "cities": [
    { "key": "Aniocha North", "label": "Aniocha North" },
    { "key": "Aniocha South", "label": "Aniocha South" },
    { "key": "Bomadi", "label": "Bomadi" },
    { "key": "Burutu", "label": "Burutu" },
    { "key": "Ethiope West", "label": "Ethiope West" },
    { "key": "Ethiope East", "label": "Ethiope East" },
    { "key": "Ika North East", "label": "Ika North East" },
    { "key": "Ika South", "label": "Ika South" },
    { "key": "Isoko North", "label": "Isoko North" },
    { "key": "Isoko South", "label": "Isoko South" },
    { "key": "Ndokwa East", "label": "Ndokwa East" },
    { "key": "Ndokwa West", "label": "Ndokwa West" },
    { "key": "Okpe", "label": "Okpe" },
    { "key": "Oshimili North", "label": "Oshimili North" },
    { "key": "Oshimili South", "label": "Oshimili South" },
    { "key": "Patani", "label": "Patani" },
    { "key": "Sapele", "label": "Sapele" },
    { "key": "Udu", "label": "Udu" },
    { "key": "Ughelli North", "label": "Ughelli North" },
    { "key": "Ukwuani", "label": "Ukwuani" },
    { "key": "Ughelli South", "label": "Ughelli South" },
    { "key": "Uvwie", "label": "Uvwie" },
    { "key": "Warri North", "label": "Warri North" },
    { "key": "Warri South", "label": "Warri South" },
    { "key": "Warri South West", "label": "Warri South West" }]
},
{
  "state": "ebonyi",
  "cities": [
    { "key": "Abakaliki", "label": "Abakaliki" },
    { "key": "Afikpo North", "label": "Afikpo North" },
    { "key": "Ebonyi", "label": "Ebonyi" },
    { "key": "Afikpo South", "label": "Afikpo South" },
    { "key": "Ezza North", "label": "Ezza North" },
    { "key": "Ikwo", "label": "Ikwo" },
    { "key": "Ezza South", "label": "Ezza South" },
    { "key": "Ivo", "label": "Ivo" },
    { "key": "Ishielu", "label": "Ishielu" },
    { "key": "Izzi", "label": "Izzi" },
    { "key": "Ohaozara", "label": "Ohaozara" },
    { "key": "Ohaukwu", "label": "Ohaukwu" },
    { "key": "Onicha", "label": "Onicha" }]
},
{
  "state": "edo",
  "cities": [
    { "key": "Akoko-Edo", "label": "Akoko-Edo" },
    { "key": "Egor", "label": "Egor" },
    { "key": "Esan Central", "label": "Esan Central" },
    { "key": "Esan North-East", "label": "Esan North-East" },
    { "key": "Esan South-East", "label": "Esan South-East" },
    { "key": "Esan West", "label": "Esan West" },
    { "key": "Etsako Central", "label": "Etsako Central" },
    { "key": "Etsako East", "label": "Etsako East" },
    { "key": "Etsako West", "label": "Etsako West" },
    { "key": "Igueben", "label": "Igueben" },
    { "key": "Ikpoba Okha", "label": "Ikpoba Okha" },
    { "key": "Orhionmwon", "label": "Orhionmwon" },
    { "key": "Oredo", "label": "Oredo" },
    { "key": "Ovia North-East", "label": "Ovia North-East" },
    { "key": "Ovia South-West", "label": "Ovia South-West" },
    { "key": "Owan East", "label": "Owan East" },
    { "key": "Owan West", "label": "Owan West" },
    { "key": "Uhunmwonde", "label": "Uhunmwonde" }]
},
{
  "state": "ekiti",
  "cities": [
    { "key": "Ado Ekiti", "label": "Ado Ekiti" },
    { "key": "Efon", "label": "Efon" },
    { "key": "Ekiti East", "label": "Ekiti East" },
    { "key": "Ekiti South-West", "label": "Ekiti South-West" },
    { "key": "Ekiti West", "label": "Ekiti West" },
    { "key": "Emure", "label": "Emure" },
    { "key": "Gbonyin", "label": "Gbonyin" },
    { "key": "Ido Osi", "label": "Ido Osi" },
    { "key": "Ijero", "label": "Ijero" },
    { "key": "Ikere", "label": "Ikere" },
    { "key": "Ilejemeje", "label": "Ilejemeje" },
    { "key": "Irepodun/Ifelodun", "label": "Irepodun/Ifelodun" },
    { "key": "Ikole", "label": "Ikole" },
    { "key": "Ise/Orun", "label": "Ise/Orun" },
    { "key": "Moba", "label": "Moba" },
    { "key": "Oye", "label": "Oye" }]
},
{
  "state": "enugu",
  "cities": [
    { "key": "Awgu", "label": "Awgu" },
    { "key": "Aninri", "label": "Aninri" },
    { "key": "Enugu East", "label": "Enugu East" },
    { "key": "Enugu North", "label": "Enugu North" },
    { "key": "Ezeagu", "label": "Ezeagu" },
    { "key": "Enugu South", "label": "Enugu South" },
    { "key": "Igbo Etiti", "label": "Igbo Etiti" },
    { "key": "Igbo Eze North", "label": "Igbo Eze North" },
    { "key": "Igbo Eze South", "label": "Igbo Eze South" },
    { "key": "Isi Uzo", "label": "Isi Uzo" },
    { "key": "Nkanu East", "label": "Nkanu East" },
    { "key": "Nkanu West", "label": "Nkanu West" },
    { "key": "Nsukka", "label": "Nsukka" },
    { "key": "Udenu", "label": "Udenu" },
    { "key": "Oji River", "label": "Oji River" },
    { "key": "Uzo Uwani", "label": "Uzo Uwani" },
    { "key": "Udi", "label": "Udi" }]
},
{
  "state": "fct",
  "cities": [
    { "key": "Abaji", "label": "Abaji" },
    { "key": "Bwari", "label": "Bwari" },
    { "key": "Gwagwalada", "label": "Gwagwalada" },
    { "key": "Kuje", "label": "Kuje" },
    { "key": "Kwali", "label": "Kwali" },
    { "key": "Municipal Area Council", "label": "Municipal Area Council" }]
},
{
  "state": "gombe",
  "cities": [
    { "key": "Akko", "label": "Akko" },
    { "key": "Balanga", "label": "Balanga" },
    { "key": "Billiri", "label": "Billiri" },
    { "key": "Dukku", "label": "Dukku" },
    { "key": "Funakaye", "label": "Funakaye" },
    { "key": "Gombe", "label": "Gombe" },
    { "key": "Kaltungo", "label": "Kaltungo" },
    { "key": "Kwami", "label": "Kwami" },
    { "key": "Nafada", "label": "Nafada" },
    { "key": "Shongom", "label": "Shongom" },
    { "key": "Yamaltu/Deba", "label": "Yamaltu/Deba" }]
},
{
  "state": "jigawa",
  "cities": [
    { "key": "Auyo", "label": "Auyo" },
    { "key": "Babura", "label": "Babura" },
    { "key": "Buji", "label": "Buji" },
    { "key": "Biriniwa", "label": "Biriniwa" },
    { "key": "Birnin Kudu", "label": "Birnin Kudu" },
    { "key": "Dutse", "label": "Dutse" },
    { "key": "Gagarawa", "label": "Gagarawa" },
    { "key": "Garki", "label": "Garki" },
    { "key": "Gumel", "label": "Gumel" },
    { "key": "Guri", "label": "Guri" },
    { "key": "Gwaram", "label": "Gwaram" },
    { "key": "Gwiwa", "label": "Gwiwa" },
    { "key": "Hadejia", "label": "Hadejia" },
    { "key": "Jahun", "label": "Jahun" },
    { "key": "Kafin Hausa", "label": "Kafin Hausa" },
    { "key": "Kazaure", "label": "Kazaure" },
    { "key": "Kiri Kasama", "label": "Kiri Kasama" },
    { "key": "Kiyawa", "label": "Kiyawa" },
    { "key": "Kaugama", "label": "Kaugama" },
    { "key": "Maigatari", "label": "Maigatari" },
    { "key": "Malam Madori", "label": "Malam Madori" },
    { "key": "Miga", "label": "Miga" },
    { "key": "Sule Tankarkar", "label": "Sule Tankarkar" },
    { "key": "Roni", "label": "Roni" },
    { "key": "Ringim", "label": "Ringim" },
    { "key": "Yankwashi", "label": "Yankwashi" },
    { "key": "Taura", "label": "Taura" }]
},
{
  "state": "oyo",
  "cities": [
    { "key": "Afijio", "label": "Afijio" },
    { "key": "Akinyele", "label": "Akinyele" },
    { "key": "Atiba", "label": "Atiba" },
    { "key": "Atisbo", "label": "Atisbo" },
    { "key": "Egbeda", "label": "Egbeda" },
    { "key": "Ibadan North", "label": "Ibadan North" },
    { "key": "Ibadan North-East", "label": "Ibadan North-East" },
    { "key": "Ibadan North-West", "label": "Ibadan North-West" },
    { "key": "Ibadan South-East", "label": "Ibadan South-East" },
    { "key": "Ibarapa Central", "label": "Ibarapa Central" },
    { "key": "Ibadan South-West", "label": "Ibadan South-West" },
    { "key": "Ibarapa East", "label": "Ibarapa East" },
    { "key": "Ido", "label": "Ido" },
    { "key": "Ibarapa North", "label": "Ibarapa North" },
    { "key": "Irepo", "label": "Irepo" },
    { "key": "Iseyin", "label": "Iseyin" },
    { "key": "Itesiwaju", "label": "Itesiwaju" },
    { "key": "Iwajowa", "label": "Iwajowa" },
    { "key": "Kajola", "label": "Kajola" },
    { "key": "Lagelu", "label": "Lagelu" },
    { "key": "Ogbomosho North", "label": "Ogbomosho North" },
    { "key": "Ogbomosho South", "label": "Ogbomosho South" },
    { "key": "Ogo Oluwa", "label": "Ogo Oluwa" },
    { "key": "Olorunsogo", "label": "Olorunsogo" },
    { "key": "Oluyole", "label": "Oluyole" },
    { "key": "Ona Ara", "label": "Ona Ara" },
    { "key": "Orelope", "label": "Orelope" },
    { "key": "Ori Ire", "label": "Ori Ire" },
    { "key": "Oyo", "label": "Oyo" },
    { "key": "Oyo East", "label": "Oyo East" },
    { "key": "Saki East", "label": "Saki East" },
    { "key": "Saki West", "label": "Saki West" },
    { "key": "Surulere Oyo State", "label": "Surulere Oyo State" }]
},
{
  "state": "imo",
  "cities": [
    { "key": "Aboh Mbaise", "label": "Aboh Mbaise" },
    { "key": "Ahiazu Mbaise", "label": "Ahiazu Mbaise" },
    { "key": "Ehime Mbano", "label": "Ehime Mbano" },
    { "key": "Ezinihitte", "label": "Ezinihitte" },
    { "key": "Ideato North", "label": "Ideato North" },
    { "key": "Ideato South", "label": "Ideato South" },
    { "key": "Ihitte/Uboma", "label": "Ihitte/Uboma" },
    { "key": "Ikeduru", "label": "Ikeduru" },
    { "key": "Isiala Mbano", "label": "Isiala Mbano" },
    { "key": "Mbaitoli", "label": "Mbaitoli" },
    { "key": "Isu", "label": "Isu" },
    { "key": "Ngor Okpala", "label": "Ngor Okpala" },
    { "key": "Njaba", "label": "Njaba" },
    { "key": "Nkwerre", "label": "Nkwerre" },
    { "key": "Nwangele", "label": "Nwangele" },
    { "key": "Obowo", "label": "Obowo" },
    { "key": "Oguta", "label": "Oguta" },
    { "key": "Ohaji/Egbema", "label": "Ohaji/Egbema" },
    { "key": "Okigwe", "label": "Okigwe" },
    { "key": "Orlu", "label": "Orlu" },
    { "key": "Orsu", "label": "Orsu" },
    { "key": "Oru East", "label": "Oru East" },
    { "key": "Oru West", "label": "Oru West" },
    { "key": "Owerri Municipal", "label": "Owerri Municipal" },
    { "key": "Owerri North", "label": "Owerri North" },
    { "key": "Unuimo", "label": "Unuimo" },
    { "key": "Owerri West", "label": "Owerri West" }]
},
{
  "state": "kaduna",
  "cities": [
    { "key": "Birnin Gwari", "label": "Birnin Gwari" },
    { "key": "Chikun", "label": "Chikun" },
    { "key": "Giwa", "label": "Giwa" },
    { "key": "Ikara", "label": "Ikara" },
    { "key": "Igabi", "label": "Igabi" },
    { "key": "Jaba", "label": "Jaba" },
    { "key": "Jema'a", "label": "Jema'a" },
    { "key": "Kachia", "label": "Kachia" },
    { "key": "Kaduna North", "label": "Kaduna North" },
    { "key": "Kaduna South", "label": "Kaduna South" },
    { "key": "Kagarko", "label": "Kagarko" },
    { "key": "Kajuru", "label": "Kajuru" },
    { "key": "Kaura", "label": "Kaura" },
    { "key": "Kauru", "label": "Kauru" },
    { "key": "Kubau", "label": "Kubau" },
    { "key": "Kudan", "label": "Kudan" },
    { "key": "Lere", "label": "Lere" },
    { "key": "Makarfi", "label": "Makarfi" },
    { "key": "Sabon Gari", "label": "Sabon Gari" },
    { "key": "Sanga", "label": "Sanga" },
    { "key": "Soba", "label": "Soba" },
    { "key": "Zangon Kataf", "label": "Zangon Kataf" },
    { "key": "Zaria", "label": "Zaria" }]
},
{
  "state": "kebbi",
  "cities": [
    { "key": "Aleiro", "label": "Aleiro" },
    { "key": "Argungu", "label": "Argungu" },
    { "key": "Arewa Dandi", "label": "Arewa Dandi" },
    { "key": "Augie", "label": "Augie" },
    { "key": "Bagudo", "label": "Bagudo" },
    { "key": "Birnin Kebbi", "label": "Birnin Kebbi" },
    { "key": "Bunza", "label": "Bunza" },
    { "key": "Dandi", "label": "Dandi" },
    { "key": "Fakai", "label": "Fakai" },
    { "key": "Gwandu", "label": "Gwandu" },
    { "key": "Jega", "label": "Jega" },
    { "key": "Kalgo", "label": "Kalgo" },
    { "key": "Koko/Besse", "label": "Koko/Besse" },
    { "key": "Maiyama", "label": "Maiyama" },
    { "key": "Ngaski", "label": "Ngaski" },
    { "key": "Shanga", "label": "Shanga" },
    { "key": "Suru", "label": "Suru" },
    { "key": "Sakaba", "label": "Sakaba" },
    { "key": "Wasagu/Danko", "label": "Wasagu/Danko" },
    { "key": "Yauri", "label": "Yauri" },
    { "key": "Zuru", "label": "Zuru" }]
},
{
  "state": "kano",
  "cities": [
    { "key": "Ajingi", "label": "Ajingi" },
    { "key": "Albasu", "label": "Albasu" },
    { "key": "Bagwai", "label": "Bagwai" },
    { "key": "Bebeji", "label": "Bebeji" },
    { "key": "Bichi", "label": "Bichi" },
    { "key": "Bunkure", "label": "Bunkure" },
    { "key": "Dala", "label": "Dala" },
    { "key": "Dambatta", "label": "Dambatta" },
    { "key": "Dawakin Kudu", "label": "Dawakin Kudu" },
    { "key": "Dawakin Tofa", "label": "Dawakin Tofa" },
    { "key": "Doguwa", "label": "Doguwa" },
    { "key": "Fagge", "label": "Fagge" },
    { "key": "Gabasawa", "label": "Gabasawa" },
    { "key": "Garko", "label": "Garko" },
    { "key": "Garun Mallam", "label": "Garun Mallam" },
    { "key": "Gezawa", "label": "Gezawa" },
    { "key": "Gaya", "label": "Gaya" },
    { "key": "Gwale", "label": "Gwale" },
    { "key": "Gwarzo", "label": "Gwarzo" },
    { "key": "Kabo", "label": "Kabo" },
    { "key": "Kano Municipal", "label": "Kano Municipal" },
    { "key": "Karaye", "label": "Karaye" },
    { "key": "Kibiya", "label": "Kibiya" },
    { "key": "Kiru", "label": "Kiru" },
    { "key": "Kumbotso", "label": "Kumbotso" },
    { "key": "Kunchi", "label": "Kunchi" },
    { "key": "Kura", "label": "Kura" },
    { "key": "Madobi", "label": "Madobi" },
    { "key": "Makoda", "label": "Makoda" },
    { "key": "Minjibir", "label": "Minjibir" },
    { "key": "Nasarawa", "label": "Nasarawa" },
    { "key": "Rano", "label": "Rano" },
    { "key": "Rimin Gado", "label": "Rimin Gado" },
    { "key": "Rogo", "label": "Rogo" },
    { "key": "Shanono", "label": "Shanono" },
    { "key": "Takai", "label": "Takai" },
    { "key": "Sumaila", "label": "Sumaila" },
    { "key": "Tarauni", "label": "Tarauni" },
    { "key": "Tofa", "label": "Tofa" },
    { "key": "Tsanyawa", "label": "Tsanyawa" },
    { "key": "Tudun Wada", "label": "Tudun Wada" },
    { "key": "Ungogo", "label": "Ungogo" },
    { "key": "Warawa", "label": "Warawa" },
    { "key": "Wudil", "label": "Wudil" }]
},
{
  "state": "kogi",
  "cities": [
    { "key": "Ajaokuta", "label": "Ajaokuta" },
    { "key": "Adavi", "label": "Adavi" },
    { "key": "Ankpa", "label": "Ankpa" },
    { "key": "Bassa", "label": "Bassa" },
    { "key": "Dekina", "label": "Dekina" },
    { "key": "Ibaji", "label": "Ibaji" },
    { "key": "Idah", "label": "Idah" },
    { "key": "Igalamela Odolu", "label": "Igalamela Odolu" },
    { "key": "Ijumu", "label": "Ijumu" },
    { "key": "Kogi", "label": "Kogi" },
    { "key": "Kabba/Bunu", "label": "Kabba/Bunu" },
    { "key": "Lokoja", "label": "Lokoja" },
    { "key": "Ofu", "label": "Ofu" },
    { "key": "Mopa Muro", "label": "Mopa Muro" },
    { "key": "Ogori/Magongo", "label": "Ogori/Magongo" },
    { "key": "Okehi", "label": "Okehi" },
    { "key": "Okene", "label": "Okene" },
    { "key": "Olamaboro", "label": "Olamaboro" },
    { "key": "Omala", "label": "Omala" },
    { "key": "Yagba East", "label": "Yagba East" },
    { "key": "Yagba West", "label": "Yagba West" }]
},
{
  "state": "osun",
  "cities": [
    { "key": "Aiyedire", "label": "Aiyedire" },
    { "key": "Atakunmosa West", "label": "Atakunmosa West" },
    { "key": "Atakunmosa East", "label": "Atakunmosa East" },
    { "key": "Aiyedaade", "label": "Aiyedaade" },
    { "key": "Boluwaduro", "label": "Boluwaduro" },
    { "key": "Boripe", "label": "Boripe" },
    { "key": "Ife East", "label": "Ife East" },
    { "key": "Ede South", "label": "Ede South" },
    { "key": "Ife North", "label": "Ife North" },
    { "key": "Ede North", "label": "Ede North" },
    { "key": "Ife South", "label": "Ife South" },
    { "key": "Ejigbo", "label": "Ejigbo" },
    { "key": "Ife Central", "label": "Ife Central" },
    { "key": "Ifedayo", "label": "Ifedayo" },
    { "key": "Egbedore", "label": "Egbedore" },
    { "key": "Ila", "label": "Ila" },
    { "key": "Ifelodun", "label": "Ifelodun" },
    { "key": "Ilesa East", "label": "Ilesa East" },
    { "key": "Ilesa West", "label": "Ilesa West" },
    { "key": "Irepodun", "label": "Irepodun" },
    { "key": "Irewole", "label": "Irewole" },
    { "key": "Isokan", "label": "Isokan" },
    { "key": "Iwo", "label": "Iwo" },
    { "key": "Obokun", "label": "Obokun" },
    { "key": "Odo Otin", "label": "Odo Otin" },
    { "key": "Ola Oluwa", "label": "Ola Oluwa" },
    { "key": "Olorunda", "label": "Olorunda" },
    { "key": "Oriade", "label": "Oriade" },
    { "key": "Orolu", "label": "Orolu" },
    { "key": "Osogbo", "label": "Osogbo" }]
},
{
  "state": "sokoto",
  "cities": [
    { "key": "Gudu", "label": "Gudu" },
    { "key": "Gwadabawa", "label": "Gwadabawa" },
    { "key": "Illela", "label": "Illela" },
    { "key": "Isa", "label": "Isa" },
    { "key": "Kebbe", "label": "Kebbe" },
    { "key": "Kware", "label": "Kware" },
    { "key": "Rabah", "label": "Rabah" },
    { "key": "Sabon Birni", "label": "Sabon Birni" },
    { "key": "Shagari", "label": "Shagari" },
    { "key": "Silame", "label": "Silame" },
    { "key": "Sokoto North", "label": "Sokoto North" },
    { "key": "Sokoto South", "label": "Sokoto South" },
    { "key": "Tambuwal", "label": "Tambuwal" },
    { "key": "Tangaza", "label": "Tangaza" },
    { "key": "Tureta", "label": "Tureta" },
    { "key": "Wamako", "label": "Wamako" },
    { "key": "Wurno", "label": "Wurno" },
    { "key": "Yabo", "label": "Yabo" },
    { "key": "Binji", "label": "Binji" },
    { "key": "Bodinga", "label": "Bodinga" },
    { "key": "Dange Shuni", "label": "Dange Shuni" },
    { "key": "Goronyo", "label": "Goronyo" },
    { "key": "Gada", "label": "Gada" }]
},
{
  "state": "plateau",
  "cities": [
    { "key": "Bokkos", "label": "Bokkos" },
    { "key": "Barkin Ladi", "label": "Barkin Ladi" },
    { "key": "Bassa", "label": "Bassa" },
    { "key": "Jos East", "label": "Jos East" },
    { "key": "Jos North", "label": "Jos North" },
    { "key": "Jos South", "label": "Jos South" },
    { "key": "Kanam", "label": "Kanam" },
    { "key": "Kanke", "label": "Kanke" },
    { "key": "Langtang South", "label": "Langtang South" },
    { "key": "Langtang North", "label": "Langtang North" },
    { "key": "Mangu", "label": "Mangu" },
    { "key": "Mikang", "label": "Mikang" },
    { "key": "Pankshin", "label": "Pankshin" },
    { "key": "Qua'an Pan", "label": "Qua'an Pan" },
    { "key": "Riyom", "label": "Riyom" },
    { "key": "Shendam", "label": "Shendam" },
    { "key": "Wase", "label": "Wase" }]
},
{
  "state": "taraba",
  "cities": [
    { "key": "Ardo Kola", "label": "Ardo Kola" },
    { "key": "Bali", "label": "Bali" },
    { "key": "Donga", "label": "Donga" },
    { "key": "Gashaka", "label": "Gashaka" },
    { "key": "Gassol", "label": "Gassol" },
    { "key": "Ibi", "label": "Ibi" },
    { "key": "Jalingo", "label": "Jalingo" },
    { "key": "Karim Lamido", "label": "Karim Lamido" },
    { "key": "Kumi", "label": "Kumi" },
    { "key": "Lau", "label": "Lau" },
    { "key": "Sardauna", "label": "Sardauna" },
    { "key": "Takum", "label": "Takum" },
    { "key": "Ussa", "label": "Ussa" },
    { "key": "Wukari", "label": "Wukari" },
    { "key": "Yorro", "label": "Yorro" },
    { "key": "Zing", "label": "Zing" }]
},
{
  "state": "yobe",
  "cities": [
    { "key": "Bade", "label": "Bade" },
    { "key": "Bursari", "label": "Bursari" },
    { "key": "Damaturu", "label": "Damaturu" },
    { "key": "Fika", "label": "Fika" },
    { "key": "Fune", "label": "Fune" },
    { "key": "Geidam", "label": "Geidam" },
    { "key": "Gujba", "label": "Gujba" },
    { "key": "Gulani", "label": "Gulani" },
    { "key": "Jakusko", "label": "Jakusko" },
    { "key": "Karasuwa", "label": "Karasuwa" },
    { "key": "Machina", "label": "Machina" },
    { "key": "Nangere", "label": "Nangere" },
    { "key": "Nguru", "label": "Nguru" },
    { "key": "Potiskum", "label": "Potiskum" },
    { "key": "Tarmuwa", "label": "Tarmuwa" },
    { "key": "Yunusari", "label": "Yunusari" },
    { "key": "Yusufari", "label": "Yusufari" }]
},
{
  "state": "zamfara",
  "cities": [
    { "key": "Anka", "label": "Anka" },
    { "key": "Birnin Magaji/Kiyaw", "label": "Birnin Magaji/Kiyaw" },
    { "key": "Bakura", "label": "Bakura" },
    { "key": "Bukkuyum", "label": "Bukkuyum" },
    { "key": "Bungudu", "label": "Bungudu" },
    { "key": "Gummi", "label": "Gummi" },
    { "key": "Gusau", "label": "Gusau" },
    { "key": "Kaura Namoda", "label": "Kaura Namoda" },
    { "key": "Maradun", "label": "Maradun" },
    { "key": "Shinkafi", "label": "Shinkafi" },
    { "key": "Maru", "label": "Maru" },
    { "key": "Talata Mafara", "label": "Talata Mafara" },
    { "key": "Tsafe", "label": "Tsafe" },
    { "key": "Zurmi", "label": "Zurmi" }]
},
{
  "state": "lagos",
  "cities": [
    { "key": "Agege", "label": "Agege" },
    { "key": "Ajeromi-Ifelodun", "label": "Ajeromi-Ifelodun" },
    { "key": "Alimosho", "label": "Alimosho" },
    { "key": "Amuwo-Odofin", "label": "Amuwo-Odofin" },
    { "key": "Badagry", "label": "Badagry" },
    { "key": "Apapa", "label": "Apapa" },
    { "key": "Epe", "label": "Epe" },
    { "key": "Eti Osa", "label": "Eti Osa" },
    { "key": "Ibeju-Lekki", "label": "Ibeju-Lekki" },
    { "key": "Ifako-Ijaiye", "label": "Ifako-Ijaiye" },
    { "key": "Ikeja", "label": "Ikeja" },
    { "key": "Ikorodu", "label": "Ikorodu" },
    { "key": "Kosofe", "label": "Kosofe" },
    { "key": "Lagos Island", "label": "Lagos Island" },
    { "key": "Mushin", "label": "Mushin" },
    { "key": "Lagos Mainland", "label": "Lagos Mainland" },
    { "key": "Ojo", "label": "Ojo" },
    { "key": "Oshodi-Isolo", "label": "Oshodi-Isolo" },
    { "key": "Shomolu", "label": "Shomolu" },
    { "key": "Surulere Lagos State", "label": "Surulere Lagos State" }]
},
{
  "state": "katsina",
  "cities": [
    { "key": "Bakori", "label": "Bakori" },
    { "key": "Batagarawa", "label": "Batagarawa" },
    { "key": "Batsari", "label": "Batsari" },
    { "key": "Baure", "label": "Baure" },
    { "key": "Bindawa", "label": "Bindawa" },
    { "key": "Charanchi", "label": "Charanchi" },
    { "key": "Danja", "label": "Danja" },
    { "key": "Dandume", "label": "Dandume" },
    { "key": "Dan Musa", "label": "Dan Musa" },
    { "key": "Daura", "label": "Daura" },
    { "key": "Dutsi", "label": "Dutsi" },
    { "key": "Dutsin Ma", "label": "Dutsin Ma" },
    { "key": "Faskari", "label": "Faskari" },
    { "key": "Funtua", "label": "Funtua" },
    { "key": "Ingawa", "label": "Ingawa" },
    { "key": "Jibia", "label": "Jibia" },
    { "key": "Kafur", "label": "Kafur" },
    { "key": "Kaita", "label": "Kaita" },
    { "key": "Kankara", "label": "Kankara" },
    { "key": "Kankia", "label": "Kankia" },
    { "key": "Katsina", "label": "Katsina" },
    { "key": "Kurfi", "label": "Kurfi" },
    { "key": "Kusada", "label": "Kusada" },
    { "key": "Mai'Adua", "label": "Mai'Adua" },
    { "key": "Malumfashi", "label": "Malumfashi" },
    { "key": "Mani", "label": "Mani" },
    { "key": "Mashi", "label": "Mashi" },
    { "key": "Matazu", "label": "Matazu" },
    { "key": "Musawa", "label": "Musawa" },
    { "key": "Rimi", "label": "Rimi" },
    { "key": "Sabuwa", "label": "Sabuwa" },
    { "key": "Safana", "label": "Safana" },
    { "key": "Sandamu", "label": "Sandamu" },
    { "key": "Zango", "label": "Zango" }]
},
{
  "state": "kwara",
  "cities": [
    { "key": "Asa", "label": "Asa" },
    { "key": "Baruten", "label": "Baruten" },
    { "key": "Edu", "label": "Edu" },
    { "key": "Ilorin East", "label": "Ilorin East" },
    { "key": "Ifelodun", "label": "Ifelodun" },
    { "key": "Ilorin South", "label": "Ilorin South" },
    { "key": "Ekiti Kwara State", "label": "Ekiti Kwara State" },
    { "key": "Ilorin West", "label": "Ilorin West" },
    { "key": "Irepodun", "label": "Irepodun" },
    { "key": "Isin", "label": "Isin" },
    { "key": "Kaiama", "label": "Kaiama" },
    { "key": "Moro", "label": "Moro" },
    { "key": "Offa", "label": "Offa" },
    { "key": "Oke Ero", "label": "Oke Ero" },
    { "key": "Oyun", "label": "Oyun" },
    { "key": "Pategi", "label": "Pategi" }]
},
{
  "state": "nasarawa",
  "cities": [
    { "key": "Akwanga", "label": "Akwanga" },
    { "key": "Awe", "label": "Awe" },
    { "key": "Doma", "label": "Doma" },
    { "key": "Karu", "label": "Karu" },
    { "key": "Keana", "label": "Keana" },
    { "key": "Keffi", "label": "Keffi" },
    { "key": "Lafia", "label": "Lafia" },
    { "key": "Kokona", "label": "Kokona" },
    { "key": "Nasarawa Egon", "label": "Nasarawa Egon" },
    { "key": "Nasarawa", "label": "Nasarawa" },
    { "key": "Obi", "label": "Obi" },
    { "key": "Toto", "label": "Toto" },
    { "key": "Wamba", "label": "Wamba" }]
},
{
  "state": "niger",
  "cities": [
    { "key": "Agaie", "label": "Agaie" },
    { "key": "Agwara", "label": "Agwara" },
    { "key": "Bida", "label": "Bida" },
    { "key": "Borgu", "label": "Borgu" },
    { "key": "Bosso", "label": "Bosso" },
    { "key": "Chanchaga", "label": "Chanchaga" },
    { "key": "Edati", "label": "Edati" },
    { "key": "Gbako", "label": "Gbako" },
    { "key": "Gurara", "label": "Gurara" },
    { "key": "Katcha", "label": "Katcha" },
    { "key": "Kontagora", "label": "Kontagora" },
    { "key": "Lapai", "label": "Lapai" },
    { "key": "Lavun", "label": "Lavun" },
    { "key": "Mariga", "label": "Mariga" },
    { "key": "Magama", "label": "Magama" },
    { "key": "Mokwa", "label": "Mokwa" },
    { "key": "Mashegu", "label": "Mashegu" },
    { "key": "Moya", "label": "Moya" },
    { "key": "Paikoro", "label": "Paikoro" },
    { "key": "Rafi", "label": "Rafi" },
    { "key": "Rijau", "label": "Rijau" },
    { "key": "Shiroro", "label": "Shiroro" },
    { "key": "Suleja", "label": "Suleja" },
    { "key": "Tafa", "label": "Tafa" },
    { "key": "Wushishi", "label": "Wushishi" }]
},
{
  "state": "abia",
  "cities": [
    { "key": "Aba North", "label": "Aba North" },
    { "key": "Arochukwu", "label": "Arochukwu" },
    { "key": "Aba South", "label": "Aba South" },
    { "key": "Bende", "label": "Bende" },
    { "key": "Isiala Ngwa North", "label": "Isiala Ngwa North" },
    { "key": "Ikwuano", "label": "Ikwuano" },
    { "key": "Isiala Ngwa South", "label": "Isiala Ngwa South" },
    { "key": "Isuikwuato", "label": "Isuikwuato" },
    { "key": "Obi Ngwa", "label": "Obi Ngwa" },
    { "key": "Ohafia", "label": "Ohafia" },
    { "key": "Osisioma", "label": "Osisioma" },
    { "key": "Ugwunagbo", "label": "Ugwunagbo" },
    { "key": "Ukwa East", "label": "Ukwa East" },
    { "key": "Ukwa West", "label": "Ukwa West" },
    { "key": "Umuahia North", "label": "Umuahia North" },
    { "key": "Umuahia South", "label": "Umuahia South" },
    { "key": "Umu Nneochi", "label": "Umu Nneochi" }]
}]