export default [
  { key: "abia", label: "Abia" },
  { key: "adamawa", label: "Adamawa" },
  { key: "akwa_ibom", label: "Akwa Ibom" },
  { key: "anambra", label: "Anambra" },
  { key: "bauchi", label: "Bauchi" },
  { key: "bayelsa", label: "Bayelsa" },
  { key: "benue", label: "Benue" },
  { key: "borno", label: "Borno" },
  { key: "cross_river", label: "Cross River" },
  { key: "delta", label: "Delta" },
  { key: "ebonyi", label: "Ebonyi" },
  { key: "edo", label: "Edo" },
  { key: "ekiti", label: "Ekiti" },
  { key: "enugu", label: "Enugu" },
  { key: "gombe", label: "Gombe" },
  { key: "imo", label: "Imo" },
  { key: "jigawa", label: "Jigawa" },
  { key: "kaduna", label: "Kaduna" },
  { key: "kano", label: "Kano" },
  { key: "katsina", label: "Katsina" },
  { key: "kebbi", label: "Kebbi" },
  { key: "kogi", label: "Kogi" },
  { key: "kwara", label: "Kwara" },
  { key: "lagos", label: "Lagos" },
  { key: "nasarawa", label: "Nasarawa" },
  { key: "niger", label: "Niger" },
  { key: "ogun", label: "Ogun" },
  { key: "ondo", label: "Ondo" },
  { key: "osun", label: "Osun" },
  { key: "oyo", label: "Oyo" },
  { key: "plateau", label: "Plateau" },
  { key: "rivers", label: "Rivers" },
  { key: "sokoto", label: "Sokoto" },
  { key: "taraba", label: "Taraba" },
  { key: "yobe", label: "Yobe" },
  { key: "zamfara", label: "Zamfara" },
  { key: "fct", label: "FCT" }
]
